require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/Documentation:
  Exclude:
    - lib/fns/error.rb